// prisma/seed.ts
import { PrismaMariaDb } from "@prisma/adapter-mariadb";
import * as dotenv from "dotenv";
import { PrismaClient } from "../generated/prisma/client";

dotenv.config();

const adapter = new PrismaMariaDb({
  host: process.env.DATABASE_HOST || "localhost",
  port: Number(process.env.DATABASE_PORT) || 3306,
  user: process.env.DATABASE_USER || "root",
  password: process.env.DATABASE_PASSWORD || "",
  database: process.env.DATABASE_NAME || "shinwoo_erp",
  connectionLimit: 5,
});

const prisma = new PrismaClient({ adapter });

async function main() {
  console.log("🌱 시딩 시작...");

  // ===== 1. 회사정보 =====
  await prisma.companyInfo.upsert({
    where: { id: 1 },
    update: {},
    create: {
      id: 1,
      companyName: "신우씨링",
      representative: "남정숙",
      address: "부산광역시 대청동2가 19번지",
      phone: "051-469-6535",
      fax: "051-464-3555",
      businessNumber: "602-36-62290",
      businessType: "제조",
      businessItem: "렛델,인쇄",
    },
  });
  console.log("✅ 회사정보");

  // ===== 2. 은행계좌 =====
  const existingAccounts = await prisma.bankAccount.count();
  if (existingAccounts === 0) {
    await prisma.bankAccount.create({
      data: {
        bankName: "하나은행",
        accountNumber: "184-890174-32205",
        accountHolder: "남정숙",
        isDefault: true,
        sortOrder: 1,
      },
    });
  }
  console.log("✅ 은행계좌");

  // ===== 3. 시스템 옵션 =====
  const optionData: { category: string; items: string[] }[] = [
    {
      category: "PRINT_TYPE",
      items: [
        "로터리",
        "디지털",
        "평압",
        "플렉소",
        "외주",
        "Zebra인쇄",
        "리본",
        "기타매입",
        "생산매입",
        "외주인쇄",
      ],
    },
    { category: "UNIT", items: ["매", "롤", "장", "EA", "박스", "부", "기타"] },
    { category: "SHAPE", items: ["사각", "원형", "특수"] },
    { category: "LAMI", items: ["투명", "무광", "유광"] },
    { category: "FOIL", items: ["금박", "은박", "청박", "적박"] },
    { category: "CUTTING_TYPE", items: ["롤", "시트"] },
    { category: "PACKAGING", items: ["비닐", "박스", "팔렛트"] },
    { category: "COURIER", items: ["CJ", "경동", "우체국"] },
    { category: "ROLL_DIR", items: ["위", "아래", "좌", "우"] },
    { category: "DATA_TYPE", items: ["기존", "수정", "신규"] },
    { category: "DESIGN_STATUS", items: ["폐기", "보유"] },
    { category: "DIE_CUTTER", items: ["보유", "주문"] },
    { category: "RESIN_PLATE", items: ["보유", "주문"] },
    {
      category: "ESTIMATE_STAGE",
      items: ["1차제안", "2차제안", "LOST", "계약체결"],
    },
    { category: "DELIVERY_METHOD", items: ["직배송", "택배"] },
  ];

  for (const { category, items } of optionData) {
    for (let i = 0; i < items.length; i++) {
      await prisma.systemOption.upsert({
        where: { category_value: { category, value: items[i] } },
        update: { sortOrder: i + 1 },
        create: {
          category,
          label: items[i],
          value: items[i],
          sortOrder: i + 1,
        },
      });
    }
  }
  console.log("✅ 시스템 옵션 (PRINT_TYPE 3개 추가 포함)");

  // ===== 4. 원단 55종 =====
  const existingMaterials = await prisma.material.count();
  if (existingMaterials === 0) {
    const materials = [
      {
        paperType: "아트지",
        backing: "그라싱지",
        adhesive: "일반(수성)",
        thickness: "90g",
        manufacturer: "부산인더스트리,제일하이텍,코스틱폼텍,드림컴퍼니,ALC",
      },
      {
        paperType: "아트지",
        backing: "그라싱지",
        adhesive: "일반(수성)",
        thickness: "80g",
        manufacturer: null,
      },
      {
        paperType: "아트지",
        backing: "아트지",
        adhesive: "일반(수성)",
        thickness: "90g",
        manufacturer: null,
      },
      {
        paperType: "모조지",
        backing: "그라싱지",
        adhesive: "일반(수성)",
        thickness: "80g",
        manufacturer: null,
      },
      {
        paperType: "모조지",
        backing: "모조지",
        adhesive: "일반(수성)",
        thickness: "80g",
        manufacturer: null,
      },
      {
        paperType: "감열지",
        backing: "그라싱지",
        adhesive: "일반(수성)",
        thickness: "60g",
        manufacturer: null,
      },
      {
        paperType: "감열지",
        backing: "그라싱지",
        adhesive: "냉동(수성)",
        thickness: "60g",
        manufacturer: null,
      },
      {
        paperType: "유포지",
        backing: "그라싱지",
        adhesive: "일반(수성)",
        thickness: "75μ",
        manufacturer: null,
      },
      {
        paperType: "유포지",
        backing: "그라싱지",
        adhesive: "강점(수성)",
        thickness: "75μ",
        manufacturer: null,
      },
      {
        paperType: "유포지",
        backing: "그라싱지",
        adhesive: "냉동(수성)",
        thickness: "75μ",
        manufacturer: null,
      },
      {
        paperType: "유포지(백색)",
        backing: "그라싱지",
        adhesive: "일반(수성)",
        thickness: "75μ",
        manufacturer: null,
      },
      {
        paperType: "유포지(투명)",
        backing: "그라싱지",
        adhesive: "일반(수성)",
        thickness: "50μ",
        manufacturer: null,
      },
      {
        paperType: "유포지(투명)",
        backing: "그라싱지",
        adhesive: "강점(수성)",
        thickness: "50μ",
        manufacturer: null,
      },
      {
        paperType: "은무늬지",
        backing: "그라싱지",
        adhesive: "일반(수성)",
        thickness: "50μ",
        manufacturer: null,
      },
      {
        paperType: "금무늬지",
        backing: "그라싱지",
        adhesive: "일반(수성)",
        thickness: "50μ",
        manufacturer: null,
      },
      {
        paperType: "은소광지",
        backing: "그라싱지",
        adhesive: "일반(수성)",
        thickness: "25μ",
        manufacturer: null,
      },
      {
        paperType: "금소광지",
        backing: "그라싱지",
        adhesive: "일반(수성)",
        thickness: "25μ",
        manufacturer: null,
      },
      {
        paperType: "백색PET",
        backing: "그라싱지",
        adhesive: "일반(수성)",
        thickness: "25μ",
        manufacturer: null,
      },
      {
        paperType: "투명PET",
        backing: "그라싱지",
        adhesive: "일반(수성)",
        thickness: "25μ",
        manufacturer: null,
      },
      {
        paperType: "투명PET",
        backing: "그라싱지",
        adhesive: "강점(수성)",
        thickness: "25μ",
        manufacturer: null,
      },
      {
        paperType: "크라프트지",
        backing: "그라싱지",
        adhesive: "일반(수성)",
        thickness: "80g",
        manufacturer: null,
      },
      {
        paperType: "크라프트지",
        backing: "크라프트지",
        adhesive: "일반(수성)",
        thickness: "80g",
        manufacturer: null,
      },
      {
        paperType: "홀로그램",
        backing: "그라싱지",
        adhesive: "일반(수성)",
        thickness: "25μ",
        manufacturer: null,
      },
      {
        paperType: "알루미늄",
        backing: "그라싱지",
        adhesive: "일반(수성)",
        thickness: "50μ",
        manufacturer: null,
      },
      {
        paperType: "PP(백색)",
        backing: "그라싱지",
        adhesive: "일반(수성)",
        thickness: "60μ",
        manufacturer: null,
      },
      {
        paperType: "PP(투명)",
        backing: "그라싱지",
        adhesive: "일반(수성)",
        thickness: "60μ",
        manufacturer: null,
      },
      {
        paperType: "PP(백색)",
        backing: "그라싱지",
        adhesive: "강점(수성)",
        thickness: "60μ",
        manufacturer: null,
      },
      {
        paperType: "PE(백색)",
        backing: "그라싱지",
        adhesive: "일반(수성)",
        thickness: "80μ",
        manufacturer: null,
      },
      {
        paperType: "PE(투명)",
        backing: "그라싱지",
        adhesive: "일반(수성)",
        thickness: "80μ",
        manufacturer: null,
      },
      {
        paperType: "파괴지",
        backing: "그라싱지",
        adhesive: "강점(수성)",
        thickness: "50μ",
        manufacturer: null,
      },
      {
        paperType: "보이드지",
        backing: "그라싱지",
        adhesive: "강점(수성)",
        thickness: "50μ",
        manufacturer: null,
      },
      {
        paperType: "로얄금지",
        backing: "그라싱지",
        adhesive: "일반(수성)",
        thickness: "80g",
        manufacturer: null,
      },
      {
        paperType: "로얄은지",
        backing: "그라싱지",
        adhesive: "일반(수성)",
        thickness: "80g",
        manufacturer: null,
      },
      {
        paperType: "OPP(투명)",
        backing: "없음",
        adhesive: "일반(수성)",
        thickness: "30μ",
        manufacturer: null,
      },
      {
        paperType: "타이벡",
        backing: "그라싱지",
        adhesive: "일반(수성)",
        thickness: "1056D",
        manufacturer: null,
      },
      {
        paperType: "면지",
        backing: "그라싱지",
        adhesive: "일반(수성)",
        thickness: "150g",
        manufacturer: null,
      },
      {
        paperType: "시찌",
        backing: "없음",
        adhesive: "없음",
        thickness: "100g",
        manufacturer: null,
      },
      {
        paperType: "재생지",
        backing: "그라싱지",
        adhesive: "일반(수성)",
        thickness: "80g",
        manufacturer: null,
      },
      {
        paperType: "열전사리본(왁스)",
        backing: null,
        adhesive: null,
        thickness: null,
        manufacturer: null,
      },
      {
        paperType: "열전사리본(레진)",
        backing: null,
        adhesive: null,
        thickness: null,
        manufacturer: null,
      },
      {
        paperType: "열전사리본(왁스레진)",
        backing: null,
        adhesive: null,
        thickness: null,
        manufacturer: null,
      },
      {
        paperType: "비닐(PE)",
        backing: null,
        adhesive: null,
        thickness: "50μ",
        manufacturer: null,
      },
      {
        paperType: "비닐(OPP)",
        backing: null,
        adhesive: null,
        thickness: "30μ",
        manufacturer: null,
      },
      {
        paperType: "무점착지",
        backing: "그라싱지",
        adhesive: "없음",
        thickness: "80g",
        manufacturer: null,
      },
      {
        paperType: "형광지(주황)",
        backing: "그라싱지",
        adhesive: "일반(수성)",
        thickness: "75g",
        manufacturer: null,
      },
      {
        paperType: "형광지(녹색)",
        backing: "그라싱지",
        adhesive: "일반(수성)",
        thickness: "75g",
        manufacturer: null,
      },
      {
        paperType: "형광지(노랑)",
        backing: "그라싱지",
        adhesive: "일반(수성)",
        thickness: "75g",
        manufacturer: null,
      },
      {
        paperType: "형광지(분홍)",
        backing: "그라싱지",
        adhesive: "일반(수성)",
        thickness: "75g",
        manufacturer: null,
      },
      {
        paperType: "빼빼로지(봉투형)",
        backing: "그라싱지",
        adhesive: "일반(수성)",
        thickness: "80g",
        manufacturer: null,
      },
      {
        paperType: "코팅지(무광)",
        backing: "그라싱지",
        adhesive: "일반(수성)",
        thickness: "80g",
        manufacturer: null,
      },
      {
        paperType: "코팅지(유광)",
        backing: "그라싱지",
        adhesive: "일반(수성)",
        thickness: "80g",
        manufacturer: null,
      },
      {
        paperType: "합성지(유포)",
        backing: "그라싱지",
        adhesive: "일반(수성)",
        thickness: "100μ",
        manufacturer: null,
      },
      {
        paperType: "합성지(PP)",
        backing: "그라싱지",
        adhesive: "일반(수성)",
        thickness: "100μ",
        manufacturer: null,
      },
      {
        paperType: "에그쉘지",
        backing: "그라싱지",
        adhesive: "강점(수성)",
        thickness: "80g",
        manufacturer: null,
      },
      {
        paperType: "기타",
        backing: null,
        adhesive: null,
        thickness: null,
        manufacturer: null,
      },
    ];

    for (let i = 0; i < materials.length; i++) {
      const mat = materials[i];
      const code = `MAT-${String(i + 1).padStart(3, "0")}`;
      await prisma.material.create({
        data: { ...mat, code },
      });
    }
  }
  console.log("✅ 원단 55종");

  // ===== 5. 거래처 270개사 =====
  const existingClients = await prisma.client.count();
  if (existingClients === 0) {
    await prisma.client.createMany({
      data: [
        { companyName: "(주) 삼진글로벌넷", contactName: "강정헌" },
        { companyName: "(주) 옵스", contactName: "김상용" },
        { companyName: "(주) 이우스", contactName: "김수경" },
        { companyName: "(주) 카스스케일코리아", contactName: "정경훈" },
        { companyName: "(주) 티케이전자", contactName: "김종길" },
        { companyName: "(주) 퍼스켐인터내셔널", contactName: "김양호" },
        { companyName: "(주)KEM", contactName: "노정덕" },
        { companyName: "(주)가나마린", contactName: "정현욱" },
        { companyName: "(주)그랜드모먼트유스호스텔", contactName: "김도환" },
        { companyName: "(주)그린피앤에스", contactName: "최재학" },
        { companyName: "(주)그린힐", contactName: "윤기철" },
        { companyName: "(주)늘푸른바다", contactName: "김세종,김형광" },
        { companyName: "(주)다인디앤씨", contactName: "전우철" },
        { companyName: "(주)대경상사", contactName: "최대희" },
        { companyName: "(주)동구밭", contactName: "노순호, 박상재" },
        { companyName: "(주)동성화인텍", contactName: "최용석" },
        { companyName: "(주)동원에프앤비", contactName: "김성용" },
        { companyName: "(주)디어스아이", contactName: "한진수 외 1명" },
        { companyName: "(주)디에스글로벌", contactName: "김근환" },
        { companyName: "(주)디에이치시스템", contactName: "김용찬" },
        { companyName: "(주)디에프씨", contactName: "황지원" },
        { companyName: "(주)디엔씨", contactName: "최종권" },
        { companyName: "(주)디원코리아", contactName: "임채훈" },
        { companyName: "(주)모닝글로리", contactName: "송익현" },
        { companyName: "(주)모아", contactName: "김종수" },
        { companyName: "(주)밀양한천", contactName: "오정훈" },
        { companyName: "(주)바우와우코리아", contactName: "김청진" },
        { companyName: "(주)부산식품", contactName: "김희규, 김사천" },
        { companyName: "(주)부산어묵", contactName: "이규생" },
        { companyName: "(주)브이엘에프(VLF)", contactName: "홍성민" },
        { companyName: "(주)비즈니스온커뮤니케이션", contactName: "노태완" },
        { companyName: "(주)사조원", contactName: "이창우" },
        { companyName: "(주)삼원특수지", contactName: "이연욱" },
        { companyName: "(주)삼정", contactName: "김성완" },
        { companyName: "(주)성산테크", contactName: "강신영" },
        { companyName: "(주)성토닉스", contactName: "안용균" },
        { companyName: "(주)세롬", contactName: "박정훈" },
        { companyName: "(주)센시텍", contactName: "박형준" },
        { companyName: "(주)신양케미칼", contactName: "엄찬아" },
        { companyName: "(주)씨앤컴", contactName: "김태균" },
        {
          companyName: "(주)아워홈 본사 마케팅",
          contactName: "구본성, 유덕상",
        },
        { companyName: "(주)아워홈영남영업소", contactName: "김길수" },
        { companyName: "(주)에스아이글로컬", contactName: "김영진" },
        { companyName: "(주)에스원 부산중앙", contactName: "남궁범외 1인" },
        { companyName: "(주)에스피 시스템즈", contactName: "정지용" },
        { companyName: "(주)엑소루브", contactName: "이민정" },
        { companyName: "(주)엔투비", contactName: "이원종" },
        { companyName: "(주)엘앤피", contactName: "장은숙" },
        { companyName: "(주)엠에스씨", contactName: "김길제,정재열" },
        { companyName: "(주)예늪", contactName: "허진원" },
        { companyName: "(주)오복식품", contactName: "채경석" },
        { companyName: "(주)온누리소방공사", contactName: "박준호" },
        { companyName: "(주)올품", contactName: "강기철" },
        { companyName: "(주)우양통상", contactName: "이손희, 이현수" },
        { companyName: "(주)원스인터내셔널", contactName: "한상돈" },
        { companyName: "(주)위펀", contactName: "김헌" },
        { companyName: "(주)윌리엄자일리톨", contactName: "강유주" },
        { companyName: "(주)이씨티", contactName: "박수진" },
        { companyName: "(주)이크레더블", contactName: "민영창" },
        { companyName: "(주)일산", contactName: "HA JEANIE JIHYUN" },
        { companyName: "(주)일산전자", contactName: "하재기" },
        { companyName: "(주)재호물산", contactName: "신호익" },
        { companyName: "(주)재호식품", contactName: "신호익" },
        { companyName: "(주)정원화학", contactName: "권진" },
        { companyName: "(주)제이앤에스", contactName: "김영재" },
        { companyName: "(주)젠푸드", contactName: "김태윤, 김길제" },
        { companyName: "(주)지이스트", contactName: "박문수" },
        { companyName: "(주)지이스트 냉동", contactName: "박문수" },
        { companyName: "(주)지지엠 인천공장", contactName: "문성호" },
        { companyName: "(주)지지엠창녕공장", contactName: "문성호" },
        { companyName: "(주)진명", contactName: "김덕진" },
        { companyName: "(주)천호엔케어 양산공장", contactName: "손동일" },
        { companyName: "(주)청아무역", contactName: "하영룡" },
        { companyName: "(주)청아무역", contactName: "하영룡" },
        { companyName: "(주)청우씨에프씨", contactName: "한명기" },
        { companyName: "(주)칠산클린업", contactName: "박헌규" },
        { companyName: "(주)카보라인코리아", contactName: "이동현" },
        { companyName: "(주)칼라런트코리아", contactName: "서해열" },
        { companyName: "(주)커뮤니케이션 창", contactName: "박지현" },
        { companyName: "(주)케이아트앤컴", contactName: "권교영" },
        { companyName: "(주)크라운볼펜", contactName: "박영생" },
        { companyName: "(주)태명약품", contactName: "김성" },
        { companyName: "(주)태영텍스타일", contactName: "강순철" },
        { companyName: "(주)토빅스", contactName: "이용관" },
        { companyName: "(주)페인트메카", contactName: "김동진, 이균혁" },
        { companyName: "(주)플렛디스", contactName: "권병헌" },
        { companyName: "(주)하나은행", contactName: "이호성" },
        { companyName: "(주)하우투본홀딩스", contactName: "이진욱" },
        { companyName: "(주)한국무역정보통신", contactName: "고진" },
        { companyName: "(주)한두화이어코트", contactName: "권오성, 권무덕" },
        { companyName: "(주)한성가공", contactName: "도종대" },
        { companyName: "(주)한신기계", contactName: "유 현 용" },
        { companyName: "(주)한일상사", contactName: "김 홍 조" },
        { companyName: "(주)한일피엠상사", contactName: "이동식" },
        { companyName: "(주)한정성", contactName: "김성식" },
        { companyName: "(주)효성어묵", contactName: "김민정" },
        { companyName: "G.S Trade", contactName: "김은식" },
        { companyName: "KOTITI 시험연구원", contactName: "김준" },
        { companyName: "㈜서브원", contactName: "이국환" },
        { companyName: "㈜엘지유플러스", contactName: "홍범식" },
        { companyName: "강수세무회계사무소", contactName: "강수구" },
        { companyName: "경현물산(주) 신평지점", contactName: "이현재" },
        { companyName: "경호전력", contactName: "강복덕" },
        { companyName: "고려비지니스", contactName: "류순자" },
        { companyName: "국제앵글", contactName: "김영길" },
        { companyName: "금강정공", contactName: "윤창섭" },
        { companyName: "금문철강(주)음성공장", contactName: "문성호" },
        { companyName: "금문철강(주)진천공장", contactName: "문성호" },
        { companyName: "금양화학주식회사", contactName: "정삼열" },
        { companyName: "금오푸드원 주식회사", contactName: "최진영" },
        { companyName: "금왕인쇄", contactName: "김장환" },
        { companyName: "금호사", contactName: "하재관" },
        { companyName: "금호산업 주식회사", contactName: "유정석" },
        { companyName: "기아(주)", contactName: "송호성,최준영" },
        { companyName: "나도산업", contactName: "김영문" },
        { companyName: "나이스 조경건설", contactName: "이연우" },
        { companyName: "네이버 주식회사", contactName: "최수연" },
        { companyName: "노무법인해냄", contactName: "김찬규" },
        { companyName: "농업회사법인 (주)가야양조장", contactName: "조이덕" },
        { companyName: "농업회사법인 (주)대광에프앤지", contactName: "안광수" },
        { companyName: "농업회사법인 (주)동서웰빙", contactName: "최보경" },
        { companyName: "농업회사법인 바로담 주식회사", contactName: "한은정" },
        {
          companyName: "농업회사법인 한국아그로바이오텍 주식회사",
          contactName: "김성우",
        },
        { companyName: "농업회사법인뉴그린푸드(주)", contactName: "신용재" },
        { companyName: "니폰페인트마린코리아주식회사", contactName: "김성민" },
        { companyName: "다모아시스템", contactName: "최낙구" },
        { companyName: "다오리과자점", contactName: "문하순 외 1 명" },
        { companyName: "다온디자인", contactName: "유효정" },
        { companyName: "닥터스한우", contactName: "이수록" },
        { companyName: "대건실업", contactName: "조정옥 외 1인" },
        { companyName: "대구한의대학교산학협력단", contactName: "황세진" },
        { companyName: "대림문화", contactName: "이상근" },
        { companyName: "대림산업", contactName: "이사열" },
        { companyName: "대우제약 주식회사", contactName: "지용훈" },
        {
          companyName: "대원제약(주)",
          contactName: "백승열, BAEK JONATHAN IN",
        },
        { companyName: "대흥비니루", contactName: "변종철" },
        { companyName: "더존에이스", contactName: "김만근" },
        { companyName: "동굴문구", contactName: "김춘묵" },
        { companyName: "동서화인켐(주)", contactName: "이영관" },
        { companyName: "동아프로세스", contactName: "이재기" },
        { companyName: "동인화학", contactName: "김종헌" },
        { companyName: "동진코팅", contactName: "김영환" },
        { companyName: "동훈산업사", contactName: "박병호" },
        { companyName: "디엠", contactName: "오현주 외" },
        { companyName: "디오션", contactName: "권도혁" },
        { companyName: "디자인큐브", contactName: "박영식" },
        { companyName: "디케이산업디자인", contactName: "강성근" },
        { companyName: "럭시플로라 유한책임회사", contactName: "신미옥" },
        { companyName: "로얄미트(ROYAL MEAT)", contactName: "허미르" },
        {
          companyName: "로얄피쉬(ROYAL FISH)",
          contactName: "TIAN SE KHO외 1명",
        },
        { companyName: "리노공업(주) 서울지점", contactName: "이채윤" },
        { companyName: "마리엘코스메틱", contactName: "곽은진" },
        { companyName: "마린트러스트", contactName: "신호익" },
        { companyName: "만덕카센타", contactName: "임용곤" },
        { companyName: "모스트(most)", contactName: "도윤우" },
        { companyName: "문교교재", contactName: "김민자" },
        { companyName: "문교에이엔씨", contactName: null },
        { companyName: "문교화학", contactName: "김민자" },
        { companyName: "문레이크 윤", contactName: "윤성혜" },
        { companyName: "미도식품", contactName: "김경자" },
        { companyName: "미도식품 유한회사", contactName: "김경자" },
        { companyName: "미도어묵 김해공항점", contactName: "김승혁" },
        { companyName: "미전사", contactName: "황재선" },
        { companyName: "민족금박", contactName: "문규오" },
        { companyName: "민족부분코팅", contactName: "김영진" },
        { companyName: "방성기계", contactName: "장완섭" },
        { companyName: "보성아이엔디(주)", contactName: "염선영" },
        { companyName: "보수합지텍", contactName: "김영철" },
        {
          companyName: "복을만드는사람들 주식회사 농업회사법인",
          contactName: "조은우",
        },
        { companyName: "부광섬유주식회사", contactName: "윤정호,윤창호" },
        { companyName: "부산대원식품주식회사", contactName: "김이균, 김옥규" },
        { companyName: "부산포장산업사", contactName: "설장희" },
        { companyName: "부산한약품", contactName: "지민형" },
        { companyName: "부영전기", contactName: "이권우" },
        { companyName: "부원종합인쇄사", contactName: "윤종선" },
        { companyName: "비비솔루션 주식회사", contactName: "문영란" },
        { companyName: "사단법인 부산명품수산물협회", contactName: "박용준" },
        { companyName: "산타 주식회사", contactName: "제한결" },
        { companyName: "산호피엔엘(주)", contactName: "최은수" },
        { companyName: "삼보수산", contactName: "강석훈" },
        { companyName: "삼보정밀화학공업(주)", contactName: "조승국" },
        { companyName: "삼색기획", contactName: "김종윤" },
        { companyName: "삼영순화 (주)", contactName: "홍성표" },
        { companyName: "삼영순화 (주) 온산공장", contactName: "홍성표" },
        { companyName: "삼진식품(주)", contactName: "박용준" },
        { companyName: "삼호지기사", contactName: "박남재" },
        { companyName: "상동화(주)", contactName: "김원기" },
        {
          companyName: "새한신용정보(주) 부산법조지사",
          contactName: "지광윤,양재혁",
        },
        { companyName: "샘프로세스", contactName: "박차진" },
        { companyName: "서울식품공업(주)", contactName: "서성훈" },
        { companyName: "석중한의원 원외탕전실", contactName: "주석중" },
        {
          companyName: "설명한의원 부설 한도깨비원외탕전실",
          contactName: "안지명 외 1명",
        },
        { companyName: "설문화인쇄사", contactName: "안흥순" },
        { companyName: "성광정판인쇄사", contactName: "김왕귀" },
        { companyName: "성남상사", contactName: "하승민" },
        { companyName: "성림원색사", contactName: "공해철" },
        { companyName: "성림칼라", contactName: "손혜경" },
        { companyName: "성화종합인쇄사", contactName: "나인식" },
        { companyName: "세신실업(주)", contactName: "이상오" },
        { companyName: "세신특판사업소", contactName: "박지혜" },
        { companyName: "세양수산 주식회사", contactName: "권정하" },
        { companyName: "세영공조", contactName: "김성곤" },
        { companyName: "세움기획", contactName: "강재성" },
        { companyName: "세한포장공업사", contactName: "박무웅" },
        { companyName: "소망기업박스바다", contactName: "김경숙" },
        { companyName: "송남지업사", contactName: "정준기" },
        { companyName: "수정식품", contactName: "고대헌" },
        { companyName: "순천스티카", contactName: "김동환" },
        { companyName: "스타루스", contactName: "이길우" },
        {
          companyName: "스탠포드호텔매니지먼트 주식회사",
          contactName: "권태호",
        },
        { companyName: "신성프리미엄", contactName: "이상환" },
        { companyName: "신안디자인", contactName: "전원석" },
        { companyName: "신우컴퓨터", contactName: "이명순" },
        { companyName: "신진특수인쇄사", contactName: "강맹호" },
        { companyName: "썬라이즈", contactName: "노도환" },
        { companyName: "썬맥스", contactName: "노제환" },
        { companyName: "씨제이대한통운㈜", contactName: "신영수,민영학" },
        { companyName: "아크릴몰", contactName: "장소영" },
        { companyName: "알찬식품", contactName: "민복기" },
        { companyName: "알피니언메디칼시스템(주)", contactName: "이인규" },
        { companyName: "약손한의원", contactName: "이관형" },
        { companyName: "에스앤제이텍", contactName: "류 재수" },
        { companyName: "에스케이쉴더스(주) 부산지점", contactName: "민기식" },
        { companyName: "에쓰비기술경영자문 협동조합", contactName: "최성욱" },
        { companyName: "에이덴 주식회사", contactName: "이승훈" },
        { companyName: "에이스테크", contactName: "이상" },
        { companyName: "에이치비 코퍼레이션 주식회사", contactName: "이시호" },
        { companyName: "엘코엔지니어링주식회사", contactName: "송국근" },
        { companyName: "엠티엘", contactName: "정종희" },
        { companyName: "영신상사", contactName: "김옥희" },
        {
          companyName: "오제이씨 (주) 울산공장",
          contactName: "송태진, 남훈모",
        },
        { companyName: "올칼라북제작소", contactName: "김정화" },
        { companyName: "와이드", contactName: "이상수" },
        { companyName: "울산원예농협 율리사업소", contactName: "김철준" },
        { companyName: "원랩프린테크", contactName: "박준우" },
        { companyName: "위한식품", contactName: "김성완" },
        { companyName: "유니크바이오텍 주식회사", contactName: "허용갑" },
        { companyName: "유진봉투사", contactName: "팽 현 기" },
        { companyName: "유한회사 피피지코리아", contactName: "구본광" },
        {
          companyName: "의료법인 은경의료재단(인창대연요양병원)",
          contactName: "염순원",
        },
        {
          companyName: "의료법인 은경의료재단(인창병원)",
          contactName: "염순원",
        },
        { companyName: "이도통상(주)", contactName: "권태호" },
        { companyName: "이브이브씨(EVEVC)", contactName: "이혜경" },
        { companyName: "이에스 케미칼(주)", contactName: "김해욱" },
        { companyName: "이진S&T", contactName: "김예은" },
        {
          companyName: "이카운트",
          contactName: "김신래",
          phone: "070-4034-5500",
        },
        { companyName: "인더스마켓(INDUSMARKET)", contactName: "황보민호" },
        { companyName: "인쇄마당 주식회사", contactName: "안풍" },
        { companyName: "인제대학교 산학협력단", contactName: "손근용" },
        { companyName: "일원플러스", contactName: "신만식" },
        { companyName: "자연과발효", contactName: "김종열" },
        { companyName: "점자출판디오티(DOT)", contactName: "최정규" },
        { companyName: "정인수산", contactName: "이철호" },
        { companyName: "제이에스와이주식회사", contactName: "길륜정" },
        { companyName: "제이제이아이", contactName: "김민구" },
        { companyName: "제이투시스템", contactName: "진익태" },
        { companyName: "제일 모터스", contactName: "이영규" },
        { companyName: "제일종합정비", contactName: "이봉석" },
        { companyName: "제일하이텍(주)", contactName: "송태문 외1명" },
        {
          companyName: "조광요턴(주)",
          contactName: "ONG KENG CHOON ALFIE, 홍민규",
        },
        { companyName: "조광페인트(주)", contactName: "양성아" },
        { companyName: "조은상사", contactName: "강민철" },
        { companyName: "주식회사 가가산업", contactName: "정시완 외 1 명" },
        { companyName: "주식회사 경주제과", contactName: "이춘옥" },
        { companyName: "주식회사 고려식품", contactName: "권동주" },
        { companyName: "주식회사 그린피앤티", contactName: "홍은표" },
        {
          companyName: "주식회사 금오에프앤지 농업회사법인",
          contactName: "안언상",
        },
        { companyName: "주식회사 누림트레이딩", contactName: "이상진" },
        { companyName: "주식회사 당근마켓", contactName: "김용현, 황도연" },
        { companyName: "주식회사 대명에프엔디", contactName: "이민욱" },
        { companyName: "주식회사 드림컴퍼니", contactName: "김동현" },
        { companyName: "주식회사 디디피스토리", contactName: "김민지" },
        { companyName: "주식회사 디제이스퀘어", contactName: "정동진" },
        { companyName: "주식회사 로얄푸드", contactName: "장순재" },
        { companyName: "주식회사 로얄푸드할랄", contactName: "TIAN EN CHER" },
        { companyName: "주식회사 문교", contactName: "남기용, 남두석" },
        { companyName: "주식회사 문교에스티", contactName: "최정화" },
        { companyName: "주식회사 미도푸드", contactName: "정혜문" },
        { companyName: "주식회사 밀앤스토리", contactName: "오세용, 박지웅" },
        { companyName: "주식회사 베네글로우랩", contactName: "이승준" },
        { companyName: "주식회사 벨펙스", contactName: "김은지" },
        { companyName: "주식회사 부산인더스트리", contactName: "한기원" },
        { companyName: "주식회사 부원스틸", contactName: "김창도" },
        { companyName: "주식회사 뷰티포레", contactName: "손충현" },
        { companyName: "주식회사 블랑코퍼레이션", contactName: "양해욱" },
        { companyName: "주식회사 서진에프앤비", contactName: "김서진" },
        { companyName: "주식회사 서진커뮤니케이션", contactName: "김정대" },
        { companyName: "주식회사 선나래전자", contactName: "김동휘" },
        { companyName: "주식회사 선영디자인", contactName: "박선영" },
        { companyName: "주식회사 세명사", contactName: "채길수" },
        { companyName: "주식회사 스타포드인", contactName: "권용범" },
        { companyName: "주식회사 스포츠바이오텍", contactName: "조채형" },
        { companyName: "주식회사 신광", contactName: "이봉근" },
        { companyName: "주식회사 신우", contactName: "이동민" },
        { companyName: "주식회사 에스앤에스식품", contactName: "이철호" },
        { companyName: "주식회사 에스에이치엠", contactName: "김우성" },
        { companyName: "주식회사 에이치엠칼라", contactName: "이문순" },
        { companyName: "주식회사 에코더블유", contactName: "한진욱" },
        { companyName: "주식회사 에코마인", contactName: "문외숙" },
        { companyName: "주식회사 영학식품", contactName: "이상화" },
        { companyName: "주식회사 오피렉스", contactName: "윤지혁" },
        { companyName: "주식회사 우리전자", contactName: "이정희" },
        { companyName: "주식회사 원더트리", contactName: "최윤철" },
        { companyName: "주식회사 원산면옥홀딩스", contactName: "오재욱" },
        { companyName: "주식회사 위즈켐", contactName: "채명수, 이명진" },
        { companyName: "주식회사 윤후렉소", contactName: "윤섭" },
        { companyName: "주식회사 이앤에스피", contactName: "주미연" },
        { companyName: "주식회사 이클레틱", contactName: "황인진" },
        { companyName: "주식회사 제이와이에프엔비", contactName: "김인노" },
        { companyName: "주식회사 지니글로벌로지스", contactName: "노계정" },
        { companyName: "주식회사 카카오", contactName: "정신아" },
        { companyName: "주식회사 케미폴리오", contactName: "이철원" },
        { companyName: "주식회사 케이메디플러스", contactName: "정원호" },
        { companyName: "주식회사 케이티", contactName: "김영섭" },
        { companyName: "주식회사 쿠버사이언스", contactName: "조철신" },
        { companyName: "주식회사 큐디", contactName: "홍진기" },
        { companyName: "주식회사 태종로지스", contactName: "김민정" },
        { companyName: "주식회사 티앤아이솔루션", contactName: "이재훈" },
        { companyName: "주식회사 티피에이", contactName: "임완" },
        { companyName: "주식회사 펫레전드", contactName: "김재근" },
        { companyName: "주식회사 플로우컴퍼니", contactName: "윤지혜" },
        { companyName: "주식회사 플로우코스메틱", contactName: "윤지혜" },
        { companyName: "주식회사 한빛인더스트리", contactName: "김형일" },
        { companyName: "주식회사 해복", contactName: "정수연, 김근우" },
        { companyName: "주식회사 행성", contactName: "류형대, 이동찬" },
        {
          companyName: "주식회사 행성 진례공장",
          contactName: "류형대, 이동찬",
        },
        {
          companyName: "주식회사 행성디지털 김해사업장",
          contactName: "이동찬",
        },
        { companyName: "주식회사 휴온스메디텍", contactName: "하창우" },
        { companyName: "주식회사금호상사", contactName: "이승우" },
        { companyName: "주식회사문교오엔에스", contactName: "남명석" },
        {
          companyName: "주식회사보백씨엔에스 (BOBAEK C&S. , LTD)",
          contactName: "서동조",
        },
        { companyName: "주식회사콜센", contactName: "정대선" },
        { companyName: "주영산업(주)", contactName: "성호진,성준학" },
        { companyName: "중앙광고인쇄문화", contactName: "전곡지" },
        { companyName: "중원 주식회사", contactName: "김우겸" },
        { companyName: "중일유화(주)", contactName: "조재민" },
        { companyName: "지엠씨메드 주식회사", contactName: "전은주" },
        { companyName: "진영정밀", contactName: "이성종" },
        { companyName: "청십자의료재단 행복한병원", contactName: "류정건" },
        { companyName: "츄고쿠삼화페인트(주)", contactName: "유상욱" },
        { companyName: "츠카타니코리아(주)", contactName: "사칸요시테루외1명" },
        { companyName: "케이디 테크", contactName: "최다혜" },
        { companyName: "케이비(KB)트레이딩", contactName: "한미애" },
        {
          companyName: "케이제이푸드 큰집식품(KJ푸드 큰집식품)",
          contactName: "최보성",
        },
        { companyName: "케이카 주식회사 부산지점", contactName: "정인국" },
        { companyName: "코리아라벨 주식회사", contactName: "김범석" },
        { companyName: "코리아이플랫폼(주)", contactName: "오승엽" },
        { companyName: "코스틱폼텍 주식회사", contactName: "김성한" },
        { companyName: "코웨이(주)", contactName: "서장원" },
        { companyName: "쿨슬림", contactName: "방성원" },
        { companyName: "키퓨(Keepu)", contactName: "박예지" },
        { companyName: "태남포장", contactName: "김용태" },
        { companyName: "태성사", contactName: "김성수" },
        { companyName: "태안해양경찰서", contactName: "임재수" },
        { companyName: "태화식품공업(주)", contactName: "정영진, 정장득" },
        { companyName: "통일보일러 (주)", contactName: "이윤한" },
        { companyName: "통일에스피", contactName: "김종성" },
        {
          companyName: "티와이모듈코리아 주식회사",
          contactName: "장기복, 전재황",
        },
        { companyName: "팀프 바이오(TIMP Bio)", contactName: "YIN CHUNRI" },
        { companyName: "파마코바이오 주식회사", contactName: "강성민" },
        {
          companyName: "프로미트(PROMEAT)",
          contactName: "KIM EVGENIY VALEREVICH",
        },
        {
          companyName: "피렐리코리아 유한회사",
          contactName: "Andrea lob(안드레아이옵)",
        },
        { companyName: "하나앤스틸주식회사", contactName: "정현진" },
        {
          companyName: "한국농협김치조합공동사업법인 경남지사",
          contactName: "심재성",
        },
        { companyName: "한국상사", contactName: "여실근" },
        { companyName: "한국전력공사", contactName: "김동철" },
        { companyName: "한국전자인증(주)", contactName: "신홍식" },
        { companyName: "한국컨테이너풀(주)", contactName: "서병륜, 서지영" },
        { companyName: "한국평가데이터(주)", contactName: "홍두선" },
        { companyName: "한국피엠", contactName: "김홍식" },
        { companyName: "한다컴퍼니", contactName: "박주희" },
        { companyName: "한마음인쇄사", contactName: "유덕현" },
        { companyName: "한빛상사", contactName: "김형일" },
        { companyName: "한서통운", contactName: "김경근" },
        { companyName: "한성모직(주)", contactName: "도종호" },
        { companyName: "한창물산(주)", contactName: "박종배" },
        { companyName: "해참부산미도어묵", contactName: "정혜문" },
        { companyName: "헴펠코리아 (주)", contactName: "주석연" },
        { companyName: "현대포장사", contactName: "심 정보" },
        { companyName: "홍대OA사무용가구", contactName: "진훈" },
        { companyName: "홍진실업(주)", contactName: "박철민,배갑주" },
        { companyName: "흥진인쇄사", contactName: "김우진" },
        { companyName: "희창물산(주)", contactName: "권중천" },
        { companyName: "（주）삼원판지", contactName: "김삼연" },
        { companyName: "（주）세영애드인", contactName: "염태수" },
        { companyName: "（주）썬엘테크", contactName: "이윤호" },
        { companyName: "（주）현대페이퍼", contactName: "태원준" },
      ],
    });
  }
  console.log("✅ 거래처 270개사");

  // ===== 6. 품목 297개 =====
  const existingProducts = await prisma.product.count();
  if (existingProducts === 0) {
    await prisma.product.createMany({
      data: [
        {
          productCode: "00001",
          productName: "윌리엄자일리톨-자일리톨스톤커피한잔-앞면(1만매이상)",
          spec: "64*64",
        },
        {
          productCode: "00002",
          productName: "조광요턴-전면보라",
          spec: "154*150",
        },
        {
          productCode: "00003",
          productName: "조광요턴-전면파랑",
          spec: "154*150",
        },
        {
          productCode: "00004",
          productName: "조광요턴-전면빨강",
          spec: "154*150",
        },
        {
          productCode: "00005",
          productName: "조광요턴-전면노랑",
          spec: "154*150",
        },
        {
          productCode: "00006",
          productName: "조광요턴-흰색무지롤",
          spec: "154*150",
        },
        {
          productCode: "00007",
          productName: "조광요턴-적색띠",
          spec: "154*150",
        },
        {
          productCode: "00008",
          productName: "조광요턴-파랑색띠",
          spec: "154*150",
        },
        {
          productCode: "00009",
          productName: "조광요턴-보라색띠",
          spec: "154*150",
        },
        {
          productCode: "00010",
          productName: "조광요턴-노랑색띠",
          spec: "154*150",
        },
        {
          productCode: "00011",
          productName: "조광요턴-녹색띠",
          spec: "154*150",
        },
        {
          productCode: "00012",
          productName: "조광요턴-회색띠",
          spec: "154*150",
        },
        {
          productCode: "00013",
          productName: "조광요턴-다이아4칸-대",
          spec: "154*150",
        },
        {
          productCode: "00014",
          productName: "조광요턴-다이아4칸-소",
          spec: "154*150",
        },
        {
          productCode: "00015",
          productName: "조광요턴-다이아6칸-대",
          spec: "120*296",
        },
        {
          productCode: "00016",
          productName: "조광요턴-다이아6칸-소",
          spec: "80*198",
        },
        {
          productCode: "00017",
          productName: "희창물산-G050717 효성무직타이거 약과",
          spec: "75*55",
        },
        {
          productCode: "00018",
          productName: "조광요턴-다이아5칸-GHS",
          spec: "154*150",
        },
        {
          productCode: "00019",
          productName: "조광요턴-물고기+불꽃",
          spec: "100*200",
        },
        {
          productCode: "00020",
          productName: "청우CFC 영문 보라색 큰라벨",
          spec: "150*185",
        },
        {
          productCode: "00021",
          productName: "청우CFC 내수 파란색 큰라벨",
          spec: "150*185",
        },
        {
          productCode: "00022",
          productName: "청우CFC UN NO.1263",
          spec: "190*130",
        },
        {
          productCode: "00023",
          productName: "조광요턴-해골+물고기",
          spec: "100*200",
        },
        {
          productCode: "00024",
          productName: "조광요턴-물고기",
          spec: "100*100",
        },
        { productCode: "00025", productName: "조광요턴-해골", spec: "100*100" },
        {
          productCode: "00026",
          productName: "조광요턴-9번스티커",
          spec: "100*100",
        },
        {
          productCode: "00027",
          productName: "조광요턴-8번스티커",
          spec: "100*100",
        },
        {
          productCode: "00028",
          productName: "조광요턴-3번불꽃",
          spec: "100*100",
        },
        {
          productCode: "00029",
          productName: "문교화학-핑거페인트 튜브 스티커100ml",
          spec: "105*47",
        },
        {
          productCode: "00030",
          productName: "조광요턴-위험물표시",
          spec: "140*160",
        },
        {
          productCode: "00031",
          productName: "조광요턴-SEAMATE M LIGHT RED/OWKDRDWVA 20L-500매",
          spec: "150*150",
        },
        {
          productCode: "00032",
          productName: "조광요턴-SEAMATE M DARK RED/OWKDRDWVA 20L-1000매",
          spec: "150*150",
        },
        {
          productCode: "00033",
          productName: "조광요턴-SEAQUANTUM PRO U LIGHT RED / OWJLRDWVA 20L",
          spec: "150*150",
        },
        {
          productCode: "00034",
          productName: "모아김치-PAC KIMCHI 측면",
          spec: "52*94",
        },
        {
          productCode: "00035",
          productName: "모아김치-PAC KIMCHI 뚜껑",
          spec: "203.4*43",
        },
        {
          productCode: "00036",
          productName: "서울식품-풀스키친고칼슘러브팔미에페스츄리생지",
          spec: "110*140",
        },
        {
          productCode: "00037",
          productName: "문교화학-우드랜드 프리마고체물간틴케이스부착스티커",
          spec: "50*50",
        },
        {
          productCode: "00038",
          productName: "다온디자인-AMINO VITAL",
          spec: "200*130",
        },
        {
          productCode: "00039",
          productName: "윌리엄자일리톨-자일리톨스톤오리지널-앞면(1만매이상)",
          spec: "64*64",
        },
        {
          productCode: "00040",
          productName: "윌리엄자일리톨-자일리톨스톤오리지널-후면(1만매이상)",
          spec: "47*47",
        },
        {
          productCode: "00041",
          productName: "윌리엄자일리톨-자일리톨스톤오리지널-앞면(1만매이하)",
          spec: "64*64",
        },
        {
          productCode: "00042",
          productName: "윌리엄자일리톨-자일리톨스톤오리지널-후면(1만매이하)",
          spec: "47*47",
        },
        {
          productCode: "00043",
          productName:
            "윌리엄자일리톨-자일리톨스톤페퍼민트부스터-앞면(1만매이상)",
          spec: "64*64",
        },
        {
          productCode: "00044",
          productName:
            "윌리엄자일리톨-자일리톨스톤페퍼민트부스터-후면(1만매이상)",
          spec: "47*47",
        },
        {
          productCode: "00045",
          productName:
            "윌리엄자일리톨-자일리톨스톤페퍼민트부스터-앞면(1만매이하)",
          spec: "64*64",
        },
        {
          productCode: "00046",
          productName:
            "윌리엄자일리톨-자일리톨스톤페퍼민트부스터-후면(1만매이하)",
          spec: "47*47",
        },
        {
          productCode: "00047",
          productName: "윌리엄자일리톨-자일리톨스톤딸기향-앞면(1만매이상)",
          spec: "64*64",
        },
        {
          productCode: "00048",
          productName: "윌리엄자일리톨-자일리톨스톤딸기향-후면(1만매이상)",
          spec: "47*47",
        },
        {
          productCode: "00049",
          productName: "윌리엄자일리톨-자일리톨스톤딸기향-앞면(1만매이하)",
          spec: "64*64",
        },
        {
          productCode: "00050",
          productName: "윌리엄자일리톨-자일리톨스톤딸기향-후면(1만매이하)",
          spec: "47*47",
        },
        {
          productCode: "00051",
          productName: "윌리엄자일리톨-자일리톨스톤레몬향-앞면(1만매이상)",
          spec: "64*64",
        },
        {
          productCode: "00052",
          productName: "윌리엄자일리톨-자일리톨스톤레몬향-후면(1만매이상)",
          spec: "47*47",
        },
        {
          productCode: "00053",
          productName: "윌리엄자일리톨-자일리톨스톤레몬향-앞면(1만매이하)",
          spec: "64*64",
        },
        {
          productCode: "00054",
          productName: "윌리엄자일리톨-자일리톨스톤청포도향-후면(1만매이하)",
          spec: "47*47",
        },
        {
          productCode: "00055",
          productName: "윌리엄자일리톨-자일리톨스톤청포도향-앞면(1만매이하)",
          spec: "64*64",
        },
        {
          productCode: "00056",
          productName: "윌리엄자일리톨-자일리톨스톤청포도향-앞면(1만매이상)",
          spec: "64*64",
        },
        {
          productCode: "00057",
          productName: "윌리엄자일리톨-자일리톨스톤청포도향-후면(1만매이상)",
          spec: "47*47",
        },
        {
          productCode: "00058",
          productName: "윌리엄자일리톨-자일리톨스톤레몬향-후면(1만매이하)",
          spec: "47*47",
        },
        {
          productCode: "00059",
          productName: "윌리엄자일리톨-자일리톨스톤커피한잔-후면(1만매이상)",
          spec: "47*47",
        },
        {
          productCode: "00060",
          productName: "윌리엄자일리톨-자일리톨스톤커피한잔-앞면(1만매이하)",
          spec: "64*64",
        },
        {
          productCode: "00061",
          productName: "윌리엄자일리톨-자일리톨스톤커피한잔-후면(1만매이하)",
          spec: "47*47",
        },
        {
          productCode: "00062",
          productName: "윌리엄자일리톨-자일리톨스톤카카오-앞면(1만매이상)",
          spec: "64*64",
        },
        {
          productCode: "00063",
          productName: "윌리엄자일리톨-자일리톨스톤카카오-후면(1만매이상)",
          spec: "47*47",
        },
        {
          productCode: "00064",
          productName: "윌리엄자일리톨-자일리톨스톤카카오-앞면(1만매이하)",
          spec: "64*64",
        },
        {
          productCode: "00065",
          productName: "윌리엄자일리톨-자일리톨스톤카카오-후면(1만매이하)",
          spec: "47*47",
        },
        {
          productCode: "00066",
          productName: "윌리엄자일리톨-자일리톨스톤레몬부스터-앞면(1만매이상)",
          spec: "64*64",
        },
        {
          productCode: "00067",
          productName: "윌리엄자일리톨-자일리톨스톤레몬부스터-후면(1만매이상)",
          spec: "47*47",
        },
        {
          productCode: "00068",
          productName: "윌리엄자일리톨-자일리톨스톤레몬부스터-앞면(1만매이하)",
          spec: "64*64",
        },
        {
          productCode: "00069",
          productName: "윌리엄자일리톨-자일리톨스톤레몬부스터-후면(1만매이하)",
          spec: "47*47",
        },
        {
          productCode: "00070",
          productName: "윌리엄자일리톨-자일리톨스톤솔잎향캔디-앞면(1만매이상)",
          spec: "64*64",
        },
        {
          productCode: "00071",
          productName: "윌리엄자일리톨-자일리톨스톤솔잎향캔디-후면(1만매이상)",
          spec: "47*47",
        },
        {
          productCode: "00072",
          productName: "윌리엄자일리톨-자일리톨스톤솔잎향캔디-앞면(1만매이하)",
          spec: "64*64",
        },
        {
          productCode: "00073",
          productName: "윌리엄자일리톨-자일리톨스톤솔잎향캔디-후면(1만매이하)",
          spec: "47*47",
        },
        {
          productCode: "00074",
          productName: "윌리엄자일리톨-자일리톨스톤치카치카-앞면(1만매이상)",
          spec: "64*64",
        },
        {
          productCode: "00075",
          productName: "윌리엄자일리톨-자일리톨스톤치카치카-후면(1만매이상)",
          spec: "47*47",
        },
        {
          productCode: "00076",
          productName: "윌리엄자일리톨-자일리톨스톤치카치카-앞면(1만매이하)",
          spec: "64*64",
        },
        {
          productCode: "00077",
          productName: "윌리엄자일리톨-자일리톨스톤치카치카-후면(1만매이하)",
          spec: "47*47",
        },
        {
          productCode: "00078",
          productName: "윌리엄자일리톨-자일리톨스톤졸음캔디-앞면(1만매이상)",
          spec: "64*64",
        },
        {
          productCode: "00079",
          productName: "윌리엄자일리톨-자일리톨스톤졸음캔디-후면(1만매이상)",
          spec: "47*47",
        },
        {
          productCode: "00080",
          productName: "윌리엄자일리톨-자일리톨스톤졸음캔디-앞면(1만매이하)",
          spec: "64*64",
        },
        {
          productCode: "00081",
          productName: "윌리엄자일리톨-자일리톨스톤졸음캔디-후면(1만매이하)",
          spec: "47*47",
        },
        {
          productCode: "00082",
          productName: "윌리엄자일리톨-두바이피스타치오캔디-앞면(1만매이상)",
          spec: "64*64",
        },
        {
          productCode: "00083",
          productName: "윌리엄자일리톨-두바이피스타치오캔디-후면(1만매이상)",
          spec: "47*47",
        },
        {
          productCode: "00084",
          productName: "윌리엄자일리톨-두바이피스타치오캔디-앞면(1만매이하)",
          spec: "64*64",
        },
        {
          productCode: "00085",
          productName: "윌리엄자일리톨-두바이피스타치오캔디-후면(1만매이하)",
          spec: "47*47",
        },
        {
          productCode: "00086",
          productName: "윌리엄자일리톨-자일리톨블랙-앞면(수량상관없음)",
          spec: "64*64",
        },
        {
          productCode: "00087",
          productName: "윌리엄자일리톨-자일리톨블랙-후면(수량상관없음)",
          spec: "47*47",
        },
        {
          productCode: "00088",
          productName:
            "윌리엄자일리톨-자일리톨페퍼민트후레쉬-앞면(수량상관없음)",
          spec: "64*64",
        },
        {
          productCode: "00089",
          productName:
            "윌리엄자일리톨-자일리톨페퍼민트후레쉬-후면(수량상관없음)",
          spec: "47*47",
        },
        {
          productCode: "00090",
          productName: "윌리엄자일리톨-자일리톨비타레몬-앞면(수량상관없음)",
          spec: "64*64",
        },
        {
          productCode: "00091",
          productName: "윌리엄자일리톨-자일리톨비타레몬-후면(수량상관없음)",
          spec: "47*47",
        },
        {
          productCode: "00092",
          productName: "밀앤스토리-ZEBRA인쇄 냉동밀떡 1KG-80매",
          spec: "100*80",
        },
        {
          productCode: "00093",
          productName: "밀앤스토리-ZEBRA인쇄 냉동밀떡볶이 1KG-750매",
          spec: "100*80",
        },
        {
          productCode: "00094",
          productName: "삼화페인트-주제 백색라벨",
          spec: "135*145",
        },
        {
          productCode: "00095",
          productName: "삼화페인트-경화제 백색라벨",
          spec: "110*125",
        },
        {
          productCode: "00096",
          productName: "삼화페인트-주제 적색라벨",
          spec: "135*145",
        },
        {
          productCode: "00097",
          productName: "삼화페인트-경화제 적색라벨",
          spec: "110*125",
        },
        {
          productCode: "00098",
          productName: "삼화페인트-수출 주제라벨",
          spec: "150*150",
        },
        {
          productCode: "00099",
          productName: "코리아E플랫폼(조광음성)-CKP000617 다이아2-1번무지롤",
          spec: "135*125",
        },
        {
          productCode: "00100",
          productName: "재호식품(영업)-유포지무지롤",
          spec: "100*40",
        },
        {
          productCode: "00101",
          productName: "재호물산(생산)-고마워 무지롤大-햅섭마크",
          spec: "100*195",
        },
        {
          productCode: "00102",
          productName: "재호물산(생산)-고마워 무지롤大-햅섭마크X",
          spec: "100*195",
        },
        {
          productCode: "00103",
          productName: "재호물산(생산)-고마워 통통해파리500g(유포지/황후지)",
          spec: "100*180",
        },
        {
          productCode: "00104",
          productName: "재호물산(생산)-게맛살1kg 전면부(무지)",
          spec: "100*48",
        },
        {
          productCode: "00105",
          productName: "재호물산(생산)-게맛살1kg 후면부(제조일자 8월22일)",
          spec: "163*133",
        },
        {
          productCode: "00106",
          productName: "재호물산(생산)-게맛살1kg 후면부(제조일자 8월23일)",
          spec: "163*133",
        },
        {
          productCode: "00107",
          productName: "재호식품(영업)-쿠팡수산-18도파란색라벨",
          spec: "80*90",
        },
        {
          productCode: "00108",
          productName: "삼영순화-H2O2 31% (S-UELM)",
          spec: "110*128",
        },
        {
          productCode: "00109",
          productName: "한정성-진한향 참기름 1.8L",
          spec: "225*80",
        },
        {
          productCode: "00110",
          productName: "한정성-진간장골드1.8L",
          spec: "225*80",
        },
        {
          productCode: "00111",
          productName: "한정성-한정성 물엿 8KG",
          spec: "120*120",
        },
        {
          productCode: "00112",
          productName: "한정성-한정성 사시미간장 500ml",
          spec: "147*60",
        },
        {
          productCode: "00113",
          productName: "에이덴-카톤라벨(블랙)W(횡방향)",
          spec: "41*137",
        },
        {
          productCode: "00114",
          productName: "문교화학-문교아크릴마카 회색",
          spec: "95*48",
        },
        {
          productCode: "00115",
          productName: "문교화학-문교아크릴마카 황토",
          spec: "95*48",
        },
        {
          productCode: "00116",
          productName: "문교화학-문교아크릴마카 밝은파랑",
          spec: "95*48",
        },
        {
          productCode: "00117",
          productName: "문교화학-문교아크릴마카 진보라",
          spec: "95*48",
        },
        {
          productCode: "00118",
          productName: "문교화학-문교아크릴마카 올리브그린",
          spec: "95*48",
        },
        {
          productCode: "00119",
          productName: "문교화학-문교아크릴마카 연주황",
          spec: "95*48",
        },
        { productCode: "00120", productName: "디엔씨-3번라벨", spec: "129*83" },
        {
          productCode: "00121",
          productName: "디엔씨-Intimar wax-110*300",
          spec: "110*300",
        },
        {
          productCode: "00122",
          productName: "디엔씨-Intimar wax-160*300",
          spec: "160*300",
        },
        {
          productCode: "00123",
          productName: "KEM-라벨N-69 WM0810",
          spec: "20*7",
        },
        {
          productCode: "00124",
          productName: "쿠버사이언스-HIPLA 국문(5000매)",
          spec: "62*32.5",
        },
        { productCode: "00125", productName: "선나래-정격", spec: "20*12" },
        { productCode: "00126", productName: "선나래-이중지", spec: "20*12" },
        { productCode: "00127", productName: "일산전자-정격", spec: "20*12" },
        {
          productCode: "00128",
          productName: "일산전자-고열라벨",
          spec: "30*12",
        },
        {
          productCode: "00129",
          productName: "예늪-금관가야 닭볶음탕1kg",
          spec: null,
        },
        { productCode: "00130", productName: "예늪-육계백숙", spec: null },
        {
          productCode: "00131",
          productName: "예늪-금관가야 닭볶음용700g",
          spec: "70*160",
        },
        {
          productCode: "00132",
          productName: "칠산-크린랩핸드브러쉬",
          spec: "135*69",
        },
        {
          productCode: "00133",
          productName: "늘푸른바다-특별기획띠지(투명)",
          spec: null,
        },
        {
          productCode: "00134",
          productName: "늘푸른바다-부산어묵띠지(녹색)",
          spec: "305*30",
        },
        {
          productCode: "00135",
          productName: "늘푸른바다-부산어묵(주황색)",
          spec: "305*30",
        },
        {
          productCode: "00136",
          productName: "희창물산-무지(50*20)",
          spec: "50*20",
        },
        {
          productCode: "00137",
          productName: "희창물산-무지(50*40)",
          spec: "50*40",
        },
        {
          productCode: "00138",
          productName: "희창물산-무지(50*60)",
          spec: "50*60",
        },
        {
          productCode: "00139",
          productName: "희창물산-무지(85*73)",
          spec: "85*73",
        },
        {
          productCode: "00140",
          productName: "희창물산-무지(100*40)",
          spec: "100*40",
        },
        {
          productCode: "00141",
          productName: "희창물산-무지(100*80)",
          spec: "100*80",
        },
        {
          productCode: "00142",
          productName: "희창물산-무지(100*100)",
          spec: "100*100",
        },
        {
          productCode: "00143",
          productName: "희창물산-왁스리본(110*300)",
          spec: "110*300",
        },
        { productCode: "00144", productName: "희창물산-택배비", spec: "기본" },
        {
          productCode: "00145",
          productName: "희창물산-제품라벨(50*20)",
          spec: "50*20",
        },
        {
          productCode: "00146",
          productName: "희창물산-제품라벨(50*40)",
          spec: "50*40",
        },
        {
          productCode: "00147",
          productName: "희창물산-제품라벨(50*60)",
          spec: "50*60",
        },
        {
          productCode: "00148",
          productName: "희창물산-제품라벨(85*73)",
          spec: "85*73",
        },
        {
          productCode: "00149",
          productName: "희창물산-제품라벨(100*40)",
          spec: "100*40",
        },
        {
          productCode: "00150",
          productName: "희창물산-제품라벨(100*80)",
          spec: "100*80",
        },
        {
          productCode: "00151",
          productName: "희창물산-제품라벨(100*100)",
          spec: "100*100",
        },
        {
          productCode: "00152",
          productName: "희창물산-박스라벨(50*40)",
          spec: "50*40",
        },
        {
          productCode: "00153",
          productName: "희창물산-박스라벨(50*60)",
          spec: "50*60",
        },
        {
          productCode: "00154",
          productName: "희창물산-박스라벨(85*73)",
          spec: "85*73",
        },
        {
          productCode: "00155",
          productName: "희창물산-박스라벨(100*80)",
          spec: "100*80",
        },
        {
          productCode: "00156",
          productName: "희창물산-박스라벨(100*100)",
          spec: "100*100",
        },
        {
          productCode: "00157",
          productName: "크라운-MP2000S(0.5)",
          spec: "25*11",
        },
        {
          productCode: "00158",
          productName: "크라운-C4R4009(0.7)",
          spec: "25*14",
        },
        {
          productCode: "00159",
          productName: "행성(진례)-바코드라벨흰색(30*12)",
          spec: "30*12",
        },
        {
          productCode: "00160",
          productName: "행성(진례)-바코드라벨주황(30*12)",
          spec: "30*12",
        },
        {
          productCode: "00161",
          productName: "행성(진례)-레진리본(40*300)",
          spec: "40*300",
        },
        {
          productCode: "00162",
          productName: "크라운-HJR500RB-05(흑색)",
          spec: "25*11",
        },
        {
          productCode: "00163",
          productName: "크라운-HJR500RNB-07(흑색)",
          spec: "25*11",
        },
        {
          productCode: "00164",
          productName: "크라운-HJR500P(흰색)",
          spec: "25*11",
        },
        {
          productCode: "00165",
          productName: "크라운-HJR500B(흑색)",
          spec: "25*11",
        },
        {
          productCode: "00166",
          productName: "크라운-OJ500B(청색)",
          spec: "25*11",
        },
        {
          productCode: "00167",
          productName: "동성화인텍-HULL라벨(하늘색)",
          spec: "130*70",
        },
        {
          productCode: "00168",
          productName: "동성화인텍-무지롤",
          spec: "50*143",
        },
        {
          productCode: "00169",
          productName: "부산어묵-수제체다말이전면(투명)",
          spec: "130*130",
        },
        {
          productCode: "00170",
          productName: "부산어묵-수제체다말이후면(투명)",
          spec: "130*130",
        },
        {
          productCode: "00171",
          productName: "조광요턴-2리터용-다이아5칸",
          spec: "150*100",
        },
        {
          productCode: "00172",
          productName: "조광요턴-2리터용-무지롤(흰색)",
          spec: "150*100",
        },
        {
          productCode: "00173",
          productName: "조광요턴-중문N10-A",
          spec: "154*150",
        },
        {
          productCode: "00174",
          productName: "조광요턴-중문N10-B",
          spec: "154*150",
        },
        {
          productCode: "00175",
          productName: "조광요턴-MCI무지롤",
          spec: "85*65",
        },
        {
          productCode: "00176",
          productName: "태화식품-쌈장500G(전면)",
          spec: "81*50",
        },
        {
          productCode: "00177",
          productName: "태화식품-쌈장500G(후면)",
          spec: "95*60",
        },
        {
          productCode: "00178",
          productName: "태화식품-범일불간장13L",
          spec: "122*107",
        },
        {
          productCode: "00179",
          productName: "태화식품-곰표진간장1.7L",
          spec: "135*105",
        },
        {
          productCode: "00180",
          productName: "태화식품-범일콩된장3KG(전면)",
          spec: "160*100",
        },
        {
          productCode: "00181",
          productName: "태화식품-범일콩된장3KG(후면)",
          spec: "160*100",
        },
        {
          productCode: "00182",
          productName: "더존에이스-버스봉인지",
          spec: "140*40",
        },
        {
          productCode: "00183",
          productName: "주영산업-다이아3칸(노루표)",
          spec: "136*56",
        },
        {
          productCode: "00184",
          productName: "설문화-BNK저축은행용",
          spec: "150*20",
        },
        {
          productCode: "00185",
          productName: "부산어묵-소비기한(65*15)",
          spec: "65*15",
        },
        {
          productCode: "00186",
          productName: "부산어묵-냉동보관",
          spec: "55*23",
        },
        {
          productCode: "00187",
          productName: "효성어묵-유포지무지롤(100*190)",
          spec: "100*190",
        },
        {
          productCode: "00188",
          productName: "효성어묵-유포지무지롤(100*150)",
          spec: "100*150",
        },
        {
          productCode: "00189",
          productName: "효성어묵-레진리본(110*300)",
          spec: "110*300",
        },
        {
          productCode: "00190",
          productName: "헴펠코리아-다이아5칸-특대",
          spec: "320*90",
        },
        {
          productCode: "00191",
          productName: "순천스티커-착지스티커(광양1공장)",
          spec: "64*120",
        },
        {
          productCode: "00192",
          productName: "헴펠코리아-컨테이너용-8번",
          spec: "245*245",
        },
        {
          productCode: "00193",
          productName: "헴펠코리아-컨테이너용-물고기",
          spec: "245*245",
        },
        {
          productCode: "00194",
          productName: "헴펠코리아-주황테두리(3469)",
          spec: "300*120",
        },
        {
          productCode: "00195",
          productName: "헴펠코리아-주황색테두리(1263)",
          spec: "300*120",
        },
        {
          productCode: "00196",
          productName: "대명F&D-무지롤(70*100)",
          spec: "70*100",
        },
        {
          productCode: "00197",
          productName: "대명F&D-왁스레진(80*300)",
          spec: "80*300",
        },
        {
          productCode: "00198",
          productName: "위즈켐-투명원형스티커",
          spec: "25*25",
        },
        {
          productCode: "00199",
          productName: "재호식품(영업)-쿠팡수산18도(파랑색)",
          spec: "80*90",
        },
        {
          productCode: "00200",
          productName: "재호물산(영업)-유포지무지롤(100*40)",
          spec: "100*40",
        },
        {
          productCode: "00201",
          productName: "대우제약-브로아이점안액0.4ml",
          spec: "27*8",
        },
        {
          productCode: "00202",
          productName: "대우제약-아이힐알점안액0.5ml",
          spec: "27*8",
        },
        {
          productCode: "00203",
          productName: "다온-AMINO(200*130)",
          spec: "200*130",
        },
        {
          productCode: "00204",
          productName: "카보라인-주황색테두리(1866)",
          spec: "300*120",
        },
        {
          productCode: "00205",
          productName: "카보라인-주황색테두리(무지용)",
          spec: "300*120",
        },
        {
          productCode: "00206",
          productName: "카보라인-컨테이너용-3번불꽃",
          spec: "245*245",
        },
        {
          productCode: "00207",
          productName: "카보라인-컨테이너용-4번불꽃",
          spec: "245*245",
        },
        {
          productCode: "00208",
          productName: "카보라인-컨테이너용-9번",
          spec: "245*245",
        },
        {
          productCode: "00209",
          productName: "카보라인-컨테이너용-물고기",
          spec: "245*245",
        },
        {
          productCode: "00210",
          productName: "에이덴-카톤라벨(검정)",
          spec: "41*137",
        },
        {
          productCode: "00211",
          productName: "희창물산-두메산건도라지(전면)",
          spec: "140*105",
        },
        {
          productCode: "00212",
          productName: "희창물산-두메산건도라지(후면)",
          spec: "118*130",
        },
        {
          productCode: "00213",
          productName: "희창물산-두메산표고버섯채(전면)",
          spec: "140*105",
        },
        {
          productCode: "00214",
          productName: "희창물산-두메산표고버섯채(후면)",
          spec: "118*130",
        },
        {
          productCode: "00215",
          productName: "엠에스씨-제품식별표시(주황색)",
          spec: "138*190",
        },
        {
          productCode: "00216",
          productName: "헴펠코리아-다이아5칸-대",
          spec: "230*120",
        },
        {
          productCode: "00217",
          productName: "헴펠코리아-다이아5칸-대(빨강색띠)",
          spec: "230*120",
        },
        {
          productCode: "00218",
          productName: "일산전자-CSA인증라벨",
          spec: "20*10",
        },
        {
          productCode: "00219",
          productName: "누림트레이딩-무지롤(40*40)",
          spec: "40*40",
        },
        {
          productCode: "00220",
          productName: "다온디자인-에코프로액1L",
          spec: "210*100",
        },
        {
          productCode: "00221",
          productName: "알피바이오-무지롤(85*50)",
          spec: "85*50",
        },
        {
          productCode: "00222",
          productName: "에이덴-차트라벨(중국)",
          spec: "33*56",
        },
        {
          productCode: "00223",
          productName: "크라운-KB038(블랙)",
          spec: "27*8",
        },
        {
          productCode: "00224",
          productName: "크라운-KB038(흰색)",
          spec: "27*8",
        },
        {
          productCode: "00225",
          productName: "크라운-KB038(피코크그린)",
          spec: "27*8",
        },
        {
          productCode: "00226",
          productName: "크라운-KB038(코랄)",
          spec: "27*8",
        },
        {
          productCode: "00227",
          productName: "크라운-HJR500B(청색)",
          spec: "25*11",
        },
        {
          productCode: "00228",
          productName: "크라운-HJR500B(적색)",
          spec: "25*11",
        },
        {
          productCode: "00229",
          productName: "크라운-HJR500B(녹색)",
          spec: "25*11",
        },
        {
          productCode: "00230",
          productName: "크라운-MTJ500-038(흑색)",
          spec: "25*11",
        },
        {
          productCode: "00231",
          productName: "크라운-MTJ500-038(청색)",
          spec: "25*11",
        },
        {
          productCode: "00232",
          productName: "크라운-MTJ500-038(적색)",
          spec: "25*11",
        },
        {
          productCode: "00233",
          productName: "크라운-MTJ500-04(흑색)",
          spec: "25*11",
        },
        {
          productCode: "00234",
          productName: "크라운-MTJ500-04(청색)",
          spec: "25*11",
        },
        {
          productCode: "00235",
          productName: "크라운-MTJ500-04(적색)",
          spec: "25*11",
        },
        {
          productCode: "00236",
          productName: "크라운-HJR500RB-05(청색)",
          spec: "25*11",
        },
        {
          productCode: "00237",
          productName: "크라운-HJR500RB-05(녹색)",
          spec: "25*11",
        },
        {
          productCode: "00238",
          productName: "크라운-HJR500RB-05(적색)",
          spec: "25*11",
        },
        {
          productCode: "00239",
          productName: "크라운-HJR500RNB-07(청색)",
          spec: "25*11",
        },
        {
          productCode: "00240",
          productName: "크라운-HJR500RNB-07(적색)",
          spec: "25*11",
        },
        {
          productCode: "00241",
          productName: "크라운-HJR500RNB-07(녹색)",
          spec: "25*11",
        },
        {
          productCode: "00242",
          productName: "크라운-HJR500N(흑색)",
          spec: "25*11",
        },
        {
          productCode: "00243",
          productName: "크라운-HJR500N(청색)",
          spec: "25*11",
        },
        {
          productCode: "00244",
          productName: "크라운-HJR500N(적색)",
          spec: "25*11",
        },
        {
          productCode: "00245",
          productName: "크라운-HJR500RH-07(하늘색)",
          spec: "25*11",
        },
        {
          productCode: "00246",
          productName: "크라운-HJR500RH-07(노랑색)",
          spec: "25*11",
        },
        {
          productCode: "00247",
          productName: "크라운-HJR500RH-07(오렌지색)",
          spec: "25*11",
        },
        {
          productCode: "00248",
          productName: "크라운-HJR500RH-07(핑크)",
          spec: "25*11",
        },
        {
          productCode: "00249",
          productName: "크라운-HJR500RH-07(연두)",
          spec: "25*11",
        },
        {
          productCode: "00250",
          productName: "크라운-HJR500RH-07(보라)",
          spec: "25*11",
        },
        {
          productCode: "00251",
          productName: "크라운-OJ500B(흑색)",
          spec: "25*11",
        },
        {
          productCode: "00252",
          productName: "크라운-OJ500B(녹색)",
          spec: "25*11",
        },
        {
          productCode: "00253",
          productName: "크라운-OJ500B(적색)",
          spec: "25*11",
        },
        {
          productCode: "00254",
          productName: "크라운-JBR700(흑색)",
          spec: "25*11",
        },
        {
          productCode: "00255",
          productName: "크라운-JBR700(청색)",
          spec: "25*11",
        },
        {
          productCode: "00256",
          productName: "크라운-JBR700(적색)",
          spec: "25*11",
        },
        {
          productCode: "00257",
          productName: "대광FG-더김치컴퍼니330G(원형)",
          spec: "75*75",
        },
        {
          productCode: "00258",
          productName: "대광FG-더김치컴퍼니500G(원형)",
          spec: "98*98",
        },
        {
          productCode: "00259",
          productName: "늘푸른바다-고단백랍스타(보라)",
          spec: null,
        },
        {
          productCode: "00260",
          productName: "늘푸른바다-어묵면",
          spec: "200*45",
        },
        {
          productCode: "00261",
          productName: "그린힐-척롤샤브600G",
          spec: "65*205",
        },
        {
          productCode: "00262",
          productName: "대광FG-호주맛김치400G(원형)",
          spec: "70*70",
        },
        {
          productCode: "00263",
          productName: "대광FG-호주맛김치400G(사각)",
          spec: "100*30",
        },
        {
          productCode: "00264",
          productName: "삼영순화-WLCT(녹색띠)",
          spec: "490*50",
        },
        {
          productCode: "00265",
          productName: "삼영순화-회수용띠(노랑색)",
          spec: "490*50",
        },
        {
          productCode: "00266",
          productName: "니폰페인트-다이아5칸(파랑색띠)",
          spec: "170*160",
        },
        {
          productCode: "00267",
          productName: "니폰페인트-파란색무지롤",
          spec: "65*35",
        },
        {
          productCode: "00268",
          productName: "일산-원형(초록색)",
          spec: "20*20",
        },
        {
          productCode: "00269",
          productName: "일산-TA2세대9번큰라벨",
          spec: "260*55",
        },
        {
          productCode: "00270",
          productName: "일산-TG탈취내장박스라벨",
          spec: "260*55",
        },
        {
          productCode: "00271",
          productName: "일산-TA2세대1번작은라벨",
          spec: "35*25",
        },
        { productCode: "00272", productName: "일산-TA2세대메뉴얼", spec: null },
        {
          productCode: "00273",
          productName: "조광페인트-자보형다이아4번",
          spec: "154*70",
        },
        {
          productCode: "00274",
          productName: "희창물산-알명란케이스150G",
          spec: "110*140*37",
        },
        {
          productCode: "00275",
          productName: "희창물산-간편명란케이스150G",
          spec: "110*140*37",
        },
        {
          productCode: "00276",
          productName: "일산-무지롤(아트지)",
          spec: "95*105",
        },
        {
          productCode: "00277",
          productName: "문교화학-바니쉬제품(255*41)",
          spec: "255*41",
        },
        {
          productCode: "00278",
          productName: "일산-공기청정설명서",
          spec: "210*297",
        },
        {
          productCode: "00279",
          productName: "문교화학-크레파스24색(전면)",
          spec: "150*110",
        },
        {
          productCode: "00280",
          productName: "문교화학-크레파스24색(후면)",
          spec: "40*70",
        },
        {
          productCode: "00281",
          productName: "휴온스-스코테린(국문적색)",
          spec: "120*140",
        },
        {
          productCode: "00282",
          productName: "휴온스-스코테린(영문적색)",
          spec: "120*140",
        },
        {
          productCode: "00283",
          productName: "휴온스-스코테린(국문주황색)",
          spec: "120*140",
        },
        {
          productCode: "00284",
          productName: "휴온스-시트로린5L",
          spec: "120*140",
        },
        {
          productCode: "00285",
          productName: "휴온스-오피크린(국문청록색)",
          spec: "120*140",
        },
        {
          productCode: "00286",
          productName: "휴온스-아트지무지롤",
          spec: "200*105",
        },
        {
          productCode: "00287",
          productName: "휴온스-헥시알2%500ml",
          spec: "120*110",
        },
        {
          productCode: "00288",
          productName: "휴온스-휴맥톤80mg-300T",
          spec: "140*45",
        },
        {
          productCode: "00289",
          productName: "휴온스-휴맥톤80mg-30T",
          spec: "135*25",
        },
        {
          productCode: "00290",
          productName: "휴온스-팜시즈-30T",
          spec: "80*27",
        },
        {
          productCode: "00291",
          productName: "휴온스-암로텐션에스-30T",
          spec: "115*28",
        },
        {
          productCode: "00292",
          productName: "휴온스-암로텐션에스-300T",
          spec: "125*35",
        },
        {
          productCode: "00293",
          productName: "휴온스-클래니즈250mg-30T",
          spec: "100*30",
        },
        {
          productCode: "00294",
          productName: "조광요턴-N10 COMP-A",
          spec: null,
        },
        {
          productCode: "00295",
          productName: "조광요턴-N10 COMO-B",
          spec: null,
        },
        {
          productCode: "00296",
          productName: "세양수산-왁스리본(90*300)",
          spec: "90*300",
        },
        {
          productCode: "00297",
          productName: "카보라인-컨테이너용-6번",
          spec: "245*245",
        },
      ],
    });
  }
  console.log("✅ 품목 297개");

  console.log("🌱 시딩 완료!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
